package DB;
// Generated Jan 18, 2016 2:42:42 AM by Hibernate Tools 4.3.1



/**
 * Advisee generated by hbm2java
 */
public class Advisee  implements java.io.Serializable {


     private Integer id;
     private Staff staff;
     private StudentPreference studentPreference;

    public Advisee() {
    }

    public Advisee(Staff staff, StudentPreference studentPreference) {
       this.staff = staff;
       this.studentPreference = studentPreference;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public StudentPreference getStudentPreference() {
        return this.studentPreference;
    }
    
    public void setStudentPreference(StudentPreference studentPreference) {
        this.studentPreference = studentPreference;
    }




}


