package DB;
// Generated Jan 18, 2016 2:42:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer companyid;
     private String name;
     private Set<StudentPreference> studentPreferencesForPref2 = new HashSet<StudentPreference>(0);
     private Set<StudentPreference> studentPreferencesForPref1 = new HashSet<StudentPreference>(0);
     private Set<StudentPreference> studentPreferencesForPref4 = new HashSet<StudentPreference>(0);
     private Set<StudentPreference> studentPreferencesForPref3 = new HashSet<StudentPreference>(0);

    public Company() {
    }

    public Company(String name, Set<StudentPreference> studentPreferencesForPref2, Set<StudentPreference> studentPreferencesForPref1, Set<StudentPreference> studentPreferencesForPref4, Set<StudentPreference> studentPreferencesForPref3) {
       this.name = name;
       this.studentPreferencesForPref2 = studentPreferencesForPref2;
       this.studentPreferencesForPref1 = studentPreferencesForPref1;
       this.studentPreferencesForPref4 = studentPreferencesForPref4;
       this.studentPreferencesForPref3 = studentPreferencesForPref3;
    }
   
    public Integer getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<StudentPreference> getStudentPreferencesForPref2() {
        return this.studentPreferencesForPref2;
    }
    
    public void setStudentPreferencesForPref2(Set<StudentPreference> studentPreferencesForPref2) {
        this.studentPreferencesForPref2 = studentPreferencesForPref2;
    }
    public Set<StudentPreference> getStudentPreferencesForPref1() {
        return this.studentPreferencesForPref1;
    }
    
    public void setStudentPreferencesForPref1(Set<StudentPreference> studentPreferencesForPref1) {
        this.studentPreferencesForPref1 = studentPreferencesForPref1;
    }
    public Set<StudentPreference> getStudentPreferencesForPref4() {
        return this.studentPreferencesForPref4;
    }
    
    public void setStudentPreferencesForPref4(Set<StudentPreference> studentPreferencesForPref4) {
        this.studentPreferencesForPref4 = studentPreferencesForPref4;
    }
    public Set<StudentPreference> getStudentPreferencesForPref3() {
        return this.studentPreferencesForPref3;
    }
    
    public void setStudentPreferencesForPref3(Set<StudentPreference> studentPreferencesForPref3) {
        this.studentPreferencesForPref3 = studentPreferencesForPref3;
    }




}


