package DB;
// Generated Jan 18, 2016 2:42:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer typeid;
     private String name;
     private Set<Login> logins = new HashSet<Login>(0);

    public Type() {
    }

    public Type(String name, Set<Login> logins) {
       this.name = name;
       this.logins = logins;
    }
   
    public Integer getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }




}


